### ISSUE TITLE
BUG: Selecting right subject's freesurfer directory in parallel processing using singularity

### ISSUE THREAD

**Issue by DocRichie94** [connectomicslab/connectomemapper3#100]
Hi All,

I used Connectome Mapper v3.0.0-RC4 singularity file for my analysis. I performed parallel processing with the  "number_of_participants_processed_in_parallel" flag for my analysis.  After running, I checked  the json files in the cmp directory and notice that the "freesurfer_subject_id" remains the same in the anatomical_config.json file for all subjects (it took the first subjects's id and used it for all). Has anyone also encounted this problem?

Best
Richard

**Comment by sebastientourbier** [comment]
Hi @DocRichie94!

Thanks for reporting this behaviour! It seems there might be bug when the subject configuration file is created from the reference configuration file! I am gonna try to replicate this on my side and correct it for the next version release!
However, note that this should not cause an issue; the freesurfer subjects directory and the subject_id are automatically set inside the pipeline so it should not use the value inside the configuration file.

Hope this helps!
Best,
Seb

**Comment by DocRichie94** [comment]
Alright.
Thanks for the response

**Comment by sebastientourbier** [comment]
This has been corrected by not saving the fields `freesurfer_subjects_dir` and `freesurfer_subjects_id` in the configuration file of the anatomical pipeline (See commit b3974b6d54c9fa101ffedfa7f50d634bc8d2b99f that addresses it). Changes gonna take effects when `v3.0.0` version will be released (which is very soon 😁!).
