### ISSUE TITLE
REF: Split classes in `cmp.bidsappmanager.gui.py` in different files

### ISSUE THREAD

**Issue by sebastientourbier** [connectomicslab/connectomemapper3#129]
@jwirsich This issue follows up with your great idea at last Brainhack to split the classes defined in `cmp.bidsappmanager.gui.py` in different files. Here comes some first ideas.

I would see the restructuration as the following:
```
cmp/
|____ bidsappmanager/
        |____ gui/
                |____ __init__.py
                |____ bidsapp.py <- CMP_BIDSAppWindow class
                |____ config.py <- CMP_ConfiguratorWindow class
                |____ qc.py <- class
                |____ main.py <- CMP_MainWindow class that imports CMP_BIDSAppWindow,
                                 CMP_ConfiguratorWindow, and  CMP_InspectorWindow classes
```
This would also require:
- to add `cmp.bidsappmanager.gui` to the `packages` list in `setup.py`
- to propagate `CMP_MainWindow` to the `cmp.bidsappmanager.gui` module (by adding the line `from .main import CMP_MainWindow` to `cmp/bidsappmanager/gui/__init__.py`) such as the `from cmp.bidsappmanager.gui import CMP_MainWindow` stays valid in `cmp/cli/cmpbidsappmanager.py` script.

What do you think?

**Comment by jwirsich** [comment]
Looks good, probably to decide if to refactor before or after merging in a EEG-Configuration tab.

**Comment by sebastientourbier** [comment]
Agree @jwirsich! Correct me if I am wrong @joanrue but for now the code in cmp.bidsappmanager have been untouched with regards the EEG pipeline. If so, I would refactor first and merge the changes in `release/v3.0.0`, which is the branch where the PR including the EEG pipeline is pointing to.
