### ISSUE TITLE
BUG: Unable to create environment from .yml in Ubuntu 20.04

### ISSUE THREAD

**Issue by MeropGont** [connectomicslab/connectomemapper3#137]
Hi everyone,

I've been struggling for days trying to create the conda environment using the provided .yml file, but I get way too many conflicts and at the end it fails (I follow the instruction exactly as written in the docs: https://connectome-mapper-3.readthedocs.io/en/latest/installation.html)
CMP3 version: v3.0.1

I've already tried adjusting the channel priority in conda, change versions of the incompatible dependencies, re-installing conda altogether etc. none of them worked.
Could it be because of my Ubuntu version?

Logs:
1. This is the error i get when I run: `$ conda env create -f conda/environment.yml`

> collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
> WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
> / WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
> done
> Solving environment: /

And this takes forever.

2. When I set the conda channel priority to strict (conda-forge as priority) it goes one step further into solving the conflicts but still takes forever and crashes at the end. Here's the log:
 `$ conda env create -f conda/environment.yml`
> Collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 2.*, but conda is ignoring the .* and treating it as 2
> WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.*, but conda is ignoring the .* and treating it as 1
> / WARNING conda.models.version:get_matcher(540): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 3.6.*, but conda is ignoring the .* and treating it as 3.6
> done
> Solving environment: / 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> 

3. One solution worked half-way: I manually installed all dependencies with the specified versions. This way I could create the environment and activate it, then installed cmpbidsappmanager, but then I cannot launch the interface, I get an inconsistency issue between h5py and hdf5. Here is the log:
 `$ cmpbidsappmanager`
> (py37cmp-gui) fateme@fateme-HP:~/connectomemapper3$ cmpbidsappmanager
> Traceback (most recent call last):
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/bin/cmpbidsappmanager", line 5, in <module>
>     from cmp.cli.cmpbidsappmanager import main
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/cli/cmpbidsappmanager.py", line 21, in <module>
>     import cmp.bidsappmanager.gui.principal
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/bidsappmanager/gui/principal.py", line 21, in <module>
>     import cmp.project
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/project.py", line 23, in <module>
>     from cmp.pipelines.diffusion import diffusion as Diffusion_pipeline
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/pipelines/diffusion/diffusion.py", line 22, in <module>
>     from cmp.stages.diffusion.diffusion import DiffusionStage
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/stages/diffusion/diffusion.py", line 18, in <module>
>     from .reconstruction import *
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmp/stages/diffusion/reconstruction.py", line 34, in <module>
>     from cmtklib.interfaces.dipy import DTIEstimateResponseSH, CSD, SHORE, MAPMRI
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/cmtklib/interfaces/dipy.py", line 16, in <module>
>     from nipype.interfaces.dipy.base import DipyDiffusionInterface, DipyBaseInterface, DipyBaseInterfaceInputSpec
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/nipype/interfaces/dipy/__init__.py", line 3, in <module>
>     from .tracks import StreamlineTractography, TrackDensityMap
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/nipype/interfaces/dipy/tracks.py", line 34, in <module>
>     from dipy.workflows import segment, tracking
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/dipy/workflows/segment.py", line 4, in <module>
>     from dipy.io.image import save_nifti, load_nifti
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/dipy/io/__init__.py", line 4, in <module>
>     from .dpy import Dpy
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/dipy/io/dpy.py", line 12, in <module>
>     import h5py
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/h5py/__init__.py", line 33, in <module>
>     from . import version
>   File "/home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/h5py/version.py", line 15, in <module>
>     from . import h5 as _h5
>   File "h5py/h5.pyx", line 1, in init h5py.h5
> ImportError: /home/fateme/miniconda3/envs/py37cmp-gui/lib/python3.7/site-packages/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
> 

Thanks!
Fatemeh

**Comment by sebastientourbier** [comment]
Hi @MeropGont !
Thanks to bring  this problem up! I am gonna make some tests on my side and let you know.
In the meantime, it would be great if you can (1) edit your comment and paste the error there, and (2) indicate which version of CMP3 you are using. Thanks in advance 😁

**Comment by sebastientourbier** [comment]
Hi @MeropGont !

I also got into a lot of troubles but I managed to get a new environment.yml that does not get stuck in the Solving Environment and does not raise any conflicts 😁 

Please find below the content:
```yaml
name: py37cmp-gui

channels:
  - conda-forge
  - aramislab
  - mrtrix3
  - anaconda

dependencies:
  - python=3.7
  - pip=21.3.1
  - numpy=1.21.5
  - matplotlib=3.5.1
  - traits=6.3.2
  - traitsui=7.2.0
  - graphviz=2.50.0
  - configparser=5.2.0
  - nipype=1.7.0
  - git-annex=8.20211123
  - pyside2=5.13.2
  - indexed_gzip=1.6.4
  - dipy=1.3.0
  - cvxpy-base=1.1.18
  - cvxpy=1.1.18
  - fsleyes=1.3.3
  - mrtrix3=3.0.3

  - pip:
      - duecredit==0.9.1
      - obspy==1.2.2
      - mne==0.24.1
      - datalad[full]==0.15.4
      - datalad-container==1.1.5
      - datalad-neuroimaging==0.3.1
      - pybids==0.8.0
      - statsmodels==0.13.1
      - networkx==2.6.3
      - pydicom==2.2.2
```
After, I activated the environment and installed with pip CMP (v3.0.1):
```bash
$ conda activate py37cmp-gui
(py37cmp-gui)$ pip install git+https://github.com/connectomicslab/connectomemapper3@v3.0.1
```
At this stage I managed to launch cmpbidsappmanager with `cmpbidsappmanager` command.

However, when selecting the dataset to load, I got into troubles with `pybids` complaining that it does not accept `extensions` . This has been changed a while ago and I do not understand how there are still some uses in the code...😬

The solution was to downgrade pybids to `0.8.0` i.e.:
```bash
(py37cmp-gui)$ pip install pybids
``` 

Then, everything seems to work 😁 Let me know!

I am currently working on a new release that will come out next week, where everything should be resolved and working with the latest version of pybids.

**Comment by MeropGont** [comment]
Hi @sebastientourbier ,

I followed what you wrote, and it worked! Ahh finally! Thanks so much:)

It would be really nice to have a CMP3 version that works with newer versions of packages, some packages have upgraded considerably during their last versions. I'm looking forward to the new release.

Thanks again:)
Fatemeh
