### ISSUE TITLE
MAINT/DOC: Possibly upgrade datalad version

### ISSUE THREAD

**Issue by jsheunis** [connectomicslab/connectomemapper3#177]
_Issue related to JOSS review: https://github.com/openjournals/joss-reviews/issues/4248_

The latest release of datalad (currently) is `0.16.2`, which contains significants improvements (including performance related). You can have a look at the [changelog](https://github.com/datalad/datalad/blob/master/CHANGELOG.md#0160-fr-apr-8-2022-----spring-cleaning) for specifics. So I would suggested upgrading your dependency version to `>=0.16.0`, although I realise that would require some testing and also documentation updates, and might not be high priority.

**Comment by jsheunis** [comment]
Another note: the environment configs specify the datalad version at `0.15.4`, while the [docs](https://connectome-mapper-3.readthedocs.io/en/latest/datalad.html) state that the datalad workflow was tested with `0.14.0`. It might be better to remove this discrepancy by ensuring that the workflow works with whatever the installed datalad version will be, and updating the docs accordingly.

**Comment by sebastientourbier** [comment]
The changelog of the new version 0.16 of datalad is indeed very big! I was not aware of it. Thank you very much :)
It should definitely need to be updated and I am adding this task with a `medium-priority` label to not delay higher priorities.

The workflow presented in the tutorial on "how adopting datalad for collaboration" should  indeed use commands that are not specific to a version.
The version of Datalad and its extensions referred here corresponds to the version I used the last time I edited and tested the tutorial. I just wanted to keep track of it.
But if this is confusing, I could either specify it better, or remove completely any mention. What do you think?
