### ISSUE TITLE
A few issues with diffusion pipeline

### ISSUE THREAD

**Issue by aswinchari** [connectomicslab/connectomemapper3#18]
Hello,

Connectome mapper is fantastic, thank you. Would like to ask a couple of questions and report 1 bug.

Q1) Is it possible to use the top-up function for distortion correction with a negative PE sequence?

Q2) I have multi-shell diffusion data but the output seems to be relatively smooth across grey matter and CSF - is it possible to use the MSMT-CSD function instead of standard CSF?

Bug1) Some of the viewing options (esp for registration checking) use fslview which has been discontinued and therefore doesn't bring up the viewer, can this please be changed to fsleyes?

Thanks,
Aswin

**Comment by sebastientourbier** [comment]
Hi Aswin,

Thanks for your interest in using CMP3 and your feedback!
Sorry for the late reply, I was on vacation and I just coming back today. 
Here is my answer point by point:

Q1) Until now only an interface to FSL eddy is implemented in CMP3 but there is no interface to topup for the moment. It is planned topup should and will also be integrated but unfortunately this is not my highest priority.

Q2) As for topup, it is not possible for the moment; I have not integrated mrtrix3 MSMT-CSD in CMP3 yet. 

I see these two points as new feature requests and will open an issue for each separately. Q1 is linked to issue #19 , Q2 is linked to issue #20. 
I cannot give you an expectation about when they would be integrated thought but I am happy to receive any contributions from you or others !

Bug 1) Could you give me more details about the error you get? (like a copy of the log file) If I understand well, you have still a version of fslview installed on your computer. On the short term I could correct the bug in calling fslview. On the long term, migration to fsleyes is planned but would require more changes. I also opened issue #21 specific to this update/bug fix request.

The quality inspector of CMP3 has been designed to facilitate the visualization of all outputs but major focus is ported on the configuration and execution and the processing pipelines. However, you can still use any viewer that you preferred outside CMP3. Intermediate outputs of each pipeline / stage / interface can be found in `<derivatives>/nipype/sub-<label>/<pipeline name>/<stage name>/<interface name>`.

As all points raised here have now its specific issue. I am closing this issue.

Best,

Sebastien

**Comment by aswinchari** [comment]
Thank you, Sebastien! Happy New Year!
