### ISSUE TITLE
BUG: Lausanne 2018 .annot files are not installed with the conda installation

### ISSUE THREAD

**Issue by mschoettner** [connectomicslab/connectomemapper3#186]
When installing CMP3 v3.0.3 via anaconda, the .annot files of the 2018 parcellation are not included in `cmtklib/data/parcellation/lausanne2018/` as they are on Github.

**Comment by sebastientourbier** [comment]
Hi @mschoettner,
Thanks for reporting this.
It looks like the same issue reported in #179, which has been resolved by #182, and is planned to be part of the upcoming v3.0.4 release, so I am closing it.
