### ISSUE TITLE
Feature Request / How to Implement: SIFT filtering for dMRI streamlines

### ISSUE THREAD

**Issue by smeisler** [connectomicslab/connectomemapper3#48]
Hello,

If I wanted to implement [SIFT](https://mrtrix.readthedocs.io/en/latest/reference/commands/tcksift.html)/[SIFT2](https://mrtrix.readthedocs.io/en/latest/reference/commands/tcksift2.html) filtering for streamlines before making the structural connectome, would the following work/be possible?

1) Make two sets of config files, one for doing all the preprocessing and tractography (anat, fmri, dmri) that stops before connectome making, and another that only does connectome production.
2) Run CMP using the first config file set
3) Run SIFT/SIFT2 filtering on the tractograms
4) Run CMP using the second config file set, so the diffusion connectome is filtered.

I think this feature would make a good addition for a MrTrix3 diffusion pipeline, and only comprises a few additional commands.

Please let me know what you think, thanks!
Steven

**Comment by sebastientourbier** [comment]
Hi Steven,

I have good news, this Nipype interface is already implemented in CMP3 here: https://github.com/connectomicslab/connectomemapper3/blob/69d50b82532af25ee544a43cdcf3c125ea9cd91f/cmtklib/interfaces/mrtrix3.py#L1334-L1361. 
I guess the easiest way would be to add this Nipype interface node to MRtrix3 sift2 directly in the tracking subworkflow. 
This means this would need the following changes:
* Updating imports from cmtklib.interfaces.mrtrix3 with FilterTractogram here:
https://github.com/connectomicslab/connectomemapper3/blob/69d50b82532af25ee544a43cdcf3c125ea9cd91f/cmp/stages/diffusion/tracking.py#L21

* Creating this new workflow node and rearranging the workflow connections here:
https://github.com/connectomicslab/connectomemapper3/blob/69d50b82532af25ee544a43cdcf3c125ea9cd91f/cmp/stages/diffusion/tracking.py#L477-L492
It will look something like:
```python
sift2 = pe.Node(interface=FilterTractogram(), name='sift2')
flow.connect([
            (inputnode, mrtrix_tracking, [('DWI', 'in_file')]),
            (mrtrix_tracking, sift2, [('tracked', 'in_tracks')]),
            (inputnode, sift2, [('DWI', 'in_fod')]),
            (sift2, converter, [('out_file', 'in_tracks')]),
            (inputnode, converter, [('wm_mask_resampled', 'in_image')]),
            (converter, outputnode, [('out_tracks', 'track_file')])
        ])
```

This will be integrated within the next release candidate I am currently working on (see PR #45). 
However, I cannot tell you exactly a date but I guess you might have all recipe to integrate it on your side in the meantime.

**Comment by smeisler** [comment]
Great, thanks! I appreciate your quick responses to all of my questions, can't wait to get this program running on my end!

**Comment by weimath** [comment]
Hi，
In the **"ref_diffusion_config.json"** file, 
when set **"mrtrix_tracking_config.sift": true**,
This is use **tcksift** in MRtrix3, but I want use **tcksift2**, what should I do？
Please, thank you very much
